/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Funciones.Config;
import Funciones.conexion;
import Funciones.sentencias;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class GestionProveedor extends javax.swing.JFrame {
sentencias sen=new sentencias();
conexion conn=new conexion();
Config conf=new Config();
boolean agrega=false;
private JTextField codigo; 
private String tabla="proveedor";
private int cantidad;
private String dato[];
private String campo="nom_proveedor";
    /**
     * Creates new form crearProveedor
     */
    public GestionProveedor() {
        initComponents();
                                this.setLocationRelativeTo(null);
                        conf.desBoton(new Object[]{btnModificar,btnGrabar,btnEliminar});
        conf.desTexto(new Object[]{txtCod,txtRuc,txtNom,txtDire,txtTel,txtCel,txtCorreo,txtContacto});
        this.setResizable(false);
    }
    
    
    public void cargarDatos(String[] titulos,String consultas,String[] dato,int cantidad,int tam[],String tabla, String campo){
 this.tabla=tabla;
 this.cantidad=cantidad;
 this.dato=dato;
 this.campo=campo;
    String consulta=consultas+this.tabla;
     sen.CargaTabla(tablaProveedores, titulos, consulta, dato, this.cantidad);
        conf.TamañoTabla(tablaProveedores, tam);  
       
}
  public void buscarElementos() throws SQLException {
   javax.swing.table.DefaultTableModel dt=(DefaultTableModel)tablaProveedores.getModel();
   int cantidadfila= dt.getRowCount();        
        for( int i=cantidadfila-1; i>=0; i--) 
              dt.removeRow(i);
     try {
         String sql="SELECT * FROM "+tabla+" where "+campo+ " LIKE '%"+txtBuscar.getText()+"%'";
         System.out.println(sql);
         ResultSet rsa=sen.consultas(sql);
        String datos[]=new String[cantidad];
      while(rsa.next()){
    for(int i=0; i<cantidad;i++){
        datos[i]=rsa.getString(dato[i]);
    }
    dt.addRow(datos);
}
    tablaProveedores.setModel(dt);
     } catch (SQLException ex) {
         Logger.getLogger(GestionProveedor.class.getName()).log(Level.SEVERE, null, ex);
     }
        
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        etiNom = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        etiCod = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        etiRuc = new javax.swing.JLabel();
        txtRuc = new javax.swing.JTextField();
        etiDire = new javax.swing.JLabel();
        txtDire = new javax.swing.JTextField();
        etiTel = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        etiCel = new javax.swing.JLabel();
        txtCel = new javax.swing.JTextField();
        etiContacto = new javax.swing.JLabel();
        txtContacto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        btnPagos = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        etiCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setBackground(new java.awt.Color(0, 0, 51));
        jLabel1.setFont(new java.awt.Font("Raleway", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        jLabel1.setText("GESTIÓN de PROVEEDORES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        etiNom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiNom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/usuarioMenu.png"))); // NOI18N
        etiNom.setText("Nombre");
        getContentPane().add(etiNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        getContentPane().add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 190, 30));

        etiCod.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiCod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/cod.png"))); // NOI18N
        etiCod.setText("Código");
        getContentPane().add(etiCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        getContentPane().add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 190, 30));

        etiRuc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiRuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/ruc.png"))); // NOI18N
        etiRuc.setText("RUC");
        getContentPane().add(etiRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        getContentPane().add(txtRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 190, 30));

        etiDire.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiDire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/dire.png"))); // NOI18N
        etiDire.setText("Dirección");
        getContentPane().add(etiDire, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));
        getContentPane().add(txtDire, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 190, 30));

        etiTel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiTel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/tel.png"))); // NOI18N
        etiTel.setText("Teléfono");
        getContentPane().add(etiTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));
        getContentPane().add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 190, 30));

        etiCel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiCel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/cel.png"))); // NOI18N
        etiCel.setText("Celular");
        getContentPane().add(etiCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));
        getContentPane().add(txtCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 190, 30));

        etiContacto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiContacto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/persons.png"))); // NOI18N
        etiContacto.setText("Contacto");
        getContentPane().add(etiContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, -1, -1));

        txtContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactoActionPerformed(evt);
            }
        });
        txtContacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContactoKeyTyped(evt);
            }
        });
        getContentPane().add(txtContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, 190, 30));

        tablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "RUC", "Nombre", "Direccion", "Teléfono", "Contacto"
            }
        ));
        tablaProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProveedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProveedores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 590, 240));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        jLabel2.setText("Buscar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, -1));

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 360, 50));

        btnEliminar.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, 120, 50));

        btnNuevo.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inserto.png"))); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 110, 50));

        btnModificar.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        btnModificar.setText("EDITAR");
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 110, 50));

        btnGrabar.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        btnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnGrabar.setText("GRABAR");
        btnGrabar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 120, 50));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/exitMenu.png"))); // NOI18N
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 350, 110, 50));

        btnHistorial.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        btnHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/documento.png"))); // NOI18N
        btnHistorial.setText("HISTORIAL DE FACTURAS");
        btnHistorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 550, 290, 60));

        btnPagos.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        btnPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/documento.png"))); // NOI18N
        btnPagos.setText("PAGOS PENDIENTES");
        btnPagos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, 290, 60));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Facturación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Raleway", 1, 14))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, 610, 110));

        etiCorreo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/correo.png"))); // NOI18N
        etiCorreo.setText("Correo");
        getContentPane().add(etiCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 190, 30));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/CErrar2.png"))); // NOI18N
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 440, 60, 50));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Raleway", 1, 14))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 610, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
                          if(conf.mensajeResp("Desea eliminar el registro", "EL SISTEMA AVISA:")) {
            sen.ejecutarBorrad("delete from proveedor where cod_proveedor=" +txtCod.getText());
        }
        Actualizar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
       String sql="select * from proveedor where cod_proveedor= "+ txtCod.getText();
        ResultSet rs=sen.consultas(sql);//recibimos la consulta en una variable ResultSet
        try {
            while(rs.next()) { //mientras hay datos en rs
                //cargamos en los campos el resultado de rs, getString obtiene el valor de
                //la base de datos segun la columna numerica.
                txtRuc.setText(rs.getString(8)); 
                txtNom.setText(rs.getString(2));
                txtDire.setText(rs.getString(3));
                txtTel.setText(rs.getString(4));
                txtCel.setText(rs.getString(5)); 
                txtContacto.setText(rs.getString(6));
                txtCorreo.setText(rs.getString(7)); 

            }

            btnNuevo.setEnabled(false);
            txtRuc.setEnabled(true);
            txtRuc.requestFocus();
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(GestionProveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
        conf.habTexto(new Object[]{txtRuc,txtNom,txtDire,txtTel,txtCel,txtCorreo,txtContacto});
        conf.habBoton(new Object[]{btnGrabar});
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
             if(conf.mensajeResp("¿Desea grabar el registro?","El sistema comunica")) {
            grabar();
            conf.limpiarTexto(new Object[]{txtCod,txtRuc,txtNom,txtDire,txtTel,txtCel,txtCorreo,txtContacto});
            conf.desTexto(new Object[]{txtCod,txtRuc,txtNom,txtDire,txtTel,txtCel,txtCorreo,txtContacto});

        }
        btnNuevo.setEnabled(true);
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void tablaProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProveedoresMouseClicked
        int var=tablaProveedores.getSelectedRow();//capturamos el valor numerico de la fila cuando le damos clic
//        ponemos los valores de la tabla en los campos especificando la fila(var)y la columna
        txtCod.setText((String) tablaProveedores.getValueAt(var, 0));
        conf.habBoton(new Object[]{btnModificar,btnEliminar});
        
    }//GEN-LAST:event_tablaProveedoresMouseClicked

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
               int can=6;
            String titulos[] = {"Codigo","RUC","Nombre","Direccion","Telefono","Contacto"};
            String consulta="SELECT * FROM "+tabla+" where "+campo+ " LIKE '%"+txtBuscar.getText()+"%'";
            System.out.print(consulta);
            String datos[]={"cod_proveedor","ruc_proveedor","nom_proveedor","dire_proveedor","tel_proveedor","contacto_proveedor"};
            sen.CargaTabla(tablaProveedores,titulos,consulta,datos,can);
            ///////////////////////
//            int ancho[]={50,90,90,90,90,90,90,90,90};
//            conf.TamañoTabla(tablaProveedores,ancho);
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
                            int mensaje= JOptionPane.showConfirmDialog(this,"¿Deseas cerrar esta ventana?","Salir",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        if(mensaje == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
         agrega=true;
        conf.desBoton(new Object[]{btnNuevo,btnModificar});
        conf.habTexto(new Object[]{txtCod,txtRuc,txtNom,txtDire,txtTel,txtCel,txtCorreo,txtContacto});
    
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactoActionPerformed

    private void txtContactoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactoKeyTyped
       conf.habBoton(new Object[]{btnGrabar});
    }//GEN-LAST:event_txtContactoKeyTyped

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Cancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed
private void grabar() {
            if(agrega) {
                if(sen.ejecutarInser("insert into proveedor values("+ txtCod.getText()+","
                         + "'" + txtNom.getText()+"',"
                        + "'" + txtDire.getText()+"',"
                        + "" + txtTel.getText()+","
                        + "" + txtCel.getText()+","
                        + "'" + txtContacto.getText()+"',"
                        + "'" + txtCorreo.getText()+"',"
                        + "'" + txtRuc.getText()+"'"
                        + ")"))
                
                conf.mensaje(3,"El sistema comunica", "Hecho");
                    
            }
             else {
                    sen.ejecutarModif("Update proveedor set ruc_proveedor='"+ txtRuc.getText()+"',"
                        + "nom_proveedor='" +txtNom.getText()+"',"
                        + "dire_proveedor='" +txtDire.getText()+"',"
                        + "tel_proveedor=" +txtTel.getText()+","
                        + "cel_proveedor=" +txtCel.getText()+","
                        + "contacto_proveedor='" +txtContacto.getText()+"',"
                        + "correo_proveedor='" +txtCorreo.getText()+"'"
                        + " where cod_proveedor= "+txtCod.getText()+"");
                
            }
                Actualizar();
                conf.limpiarTexto(new Object[]{txtCod,txtRuc,txtNom,txtDire,txtTel,txtCel,txtCorreo,txtContacto});
    }
    private void CargaProveedor() throws SQLException {
            int can=6;
            String titulos[] = {"Codigo","RUC","Nombre","Direccion","Telefono","Contacto"};
            String consulta="SELECT * FROM proveedor";
            
            String datos[]={"cod_proveedor","ruc_proveedor","nom_proveedor","dire_proveedor","tel_proveedor","contacto_proveedor"};
            sen.CargaTabla(tablaProveedores,titulos,consulta,datos,can);
            ///////////////////////
//            int ancho[]={20,90,150,90,90,90};
//            conf.TamañoTabla(tablaProveedores,ancho);
        }
        private void Actualizar() {
        try {
        CargaProveedor();
        
    } catch(SQLException ex) {
        Logger.getLogger(GestionProveedor.class.getName()).log(Level.SEVERE, null, ex);
    }
 
            
    
    }
        
                    private void Cancelar() {
        //metodo para Actualizar
        GestionProveedor asis = new GestionProveedor();
        asis.pack();
        asis.setVisible(true);
        dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPagos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel etiCel;
    private javax.swing.JLabel etiCod;
    private javax.swing.JLabel etiContacto;
    private javax.swing.JLabel etiCorreo;
    private javax.swing.JLabel etiDire;
    private javax.swing.JLabel etiNom;
    private javax.swing.JLabel etiRuc;
    private javax.swing.JLabel etiTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProveedores;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCel;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtContacto;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDire;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtRuc;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables

}
