/*
 * To change this  license header, choose License Headers in Project Properties.
 * To change this  template file, choose Tools | Templates
 * and ope n the template in the editor.
 */
package Vistas;

import Funciones.Config;
import Funciones.conexion;
import Funciones.sentencias;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class GestionCobradores extends javax.swing.JFrame {
sentencias sen=new sentencias();
conexion conn=new conexion();
Config conf=new Config();
boolean agrega=false;
private JTextField codigo; 
private String tabla="cobrador";
private int cantidad;
private String dato[];
private String campo="nom_cobrador";
    /**
     * Creates new form crearProveedor
     */
    public GestionCobradores() {
        initComponents();
        this.setLocationRelativeTo(null);
                        conf.desBoton(new Object[]{btnModificar,btnGrabar,btnEliminar});
        conf.desTexto(new Object[]{txtCod,txtNom,txtDire,txtTel,txtCel});
        this.setResizable(false);
        
    }
    
public void cargarDatos(String[] titulos,String consultas,String[] dato,int cantidad,int tam[],String tabla, String campo){
 this.tabla=tabla;
 this.cantidad=cantidad;
 this.dato=dato;
 this.campo=campo;
    String consulta=consultas+this.tabla;
     sen.CargaTabla(tablaCobradores, titulos, consulta, dato, this.cantidad);
        conf.TamañoTabla(tablaCobradores, tam);  
       
}
  public void buscarElementos() throws SQLException {
   javax.swing.table.DefaultTableModel dt=(DefaultTableModel)tablaCobradores.getModel();
   int cantidadfila= dt.getRowCount();        
        for( int i=cantidadfila-1; i>=0; i--) 
              dt.removeRow(i);
     try {
         String sql="SELECT * FROM "+tabla+" where "+campo+ " LIKE '%"+txtBuscar.getText()+"%'";
         System.out.println(sql);
         ResultSet rsa=sen.consultas(sql);
        String datos[]=new String[cantidad];
      while(rsa.next()){
    for(int i=0; i<cantidad;i++){
        datos[i]=rsa.getString(dato[i]);
    }
    dt.addRow(datos);
}
    tablaCobradores.setModel(dt);
     } catch (SQLException ex) {
         Logger.getLogger(GestionVendedores.class.getName()).log(Level.SEVERE, null, ex);
     }
        
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        etiNomCobrador = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        etiCodCobrador = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        etiDireCobrador = new javax.swing.JLabel();
        txtDire = new javax.swing.JTextField();
        etiTelCobrador = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        etiCelCobrador = new javax.swing.JLabel();
        txtCel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCobradores = new javax.swing.JTable();
        etiBuscarCobrador = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        btnCobrosRealizados = new javax.swing.JButton();
        btnCobrosPendientes = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setBackground(new java.awt.Color(0, 0, 51));
        jLabel1.setFont(new java.awt.Font("Raleway", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        jLabel1.setText("GESTIÓN de COBRADORES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        etiNomCobrador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiNomCobrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/usuarioMenu.png"))); // NOI18N
        etiNomCobrador.setText("Nombre");
        getContentPane().add(etiNomCobrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        getContentPane().add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 190, 30));

        etiCodCobrador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiCodCobrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/cod.png"))); // NOI18N
        etiCodCobrador.setText("Código");
        getContentPane().add(etiCodCobrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        getContentPane().add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 190, 30));

        etiDireCobrador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiDireCobrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/dire.png"))); // NOI18N
        etiDireCobrador.setText("Dirección");
        getContentPane().add(etiDireCobrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        txtDire.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireKeyTyped(evt);
            }
        });
        getContentPane().add(txtDire, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 190, 30));

        etiTelCobrador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiTelCobrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/tel.png"))); // NOI18N
        etiTelCobrador.setText("Teléfono");
        getContentPane().add(etiTelCobrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        getContentPane().add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 190, 30));

        etiCelCobrador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiCelCobrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/cel.png"))); // NOI18N
        etiCelCobrador.setText("Celular");
        getContentPane().add(etiCelCobrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));
        getContentPane().add(txtCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 190, 30));

        tablaCobradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Teléfono", "Celular", "Dirección"
            }
        ));
        tablaCobradores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCobradoresMouseClicked(evt);
            }
        });
        tablaCobradores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaCobradoresKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCobradores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 590, 350));

        etiBuscarCobrador.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        etiBuscarCobrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        etiBuscarCobrador.setText("Buscar");
        getContentPane().add(etiBuscarCobrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 230, 70));

        btnEliminar.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 480, 120, 50));

        btnNuevo.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inserto.png"))); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 110, 50));

        btnModificar.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        btnModificar.setText("EDITAR");
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 110, 50));

        btnGrabar.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        btnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnGrabar.setText("GRABAR");
        btnGrabar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, 120, 50));

        btnCobrosRealizados.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        btnCobrosRealizados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/documento.png"))); // NOI18N
        btnCobrosRealizados.setText("COBROS REALIZADOS");
        getContentPane().add(btnCobrosRealizados, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 590, 290, 60));

        btnCobrosPendientes.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        btnCobrosPendientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/documento.png"))); // NOI18N
        btnCobrosPendientes.setText("COBROS PENDIENTES");
        getContentPane().add(btnCobrosPendientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 590, 290, 60));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/exitMenu.png"))); // NOI18N
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 480, 80, 50));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/CErrar2.png"))); // NOI18N
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 480, 60, 50));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Facturación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Raleway", 1, 14))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, 610, 100));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Raleway", 1, 14))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 670, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
                         if(conf.mensajeResp("¿Desea eliminar el registro?", "EL SISTEMA AVISA:")) {
            sen.ejecutarBorrad("delete from cobrador where cod_cobrador=" +txtCod.getText());
        }
        Actualizar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
         String sql="select * from cobrador where cod_cobrador= "+ txtCod.getText();
        ResultSet rs=sen.consultas(sql);//recibimos la consulta en una variable ResultSet
        try {
            while(rs.next()) { //mientras hay datos en rs
                //cargamos en los campos el resultado de rs, getString obtiene el valor de
                //la base de datos segun la columna numerica.
                txtNom.setText(rs.getString(2));
                txtDire.setText(rs.getString(3));
                txtTel.setText(rs.getString(5));
                txtCel.setText(rs.getString(4));
            }

            btnNuevo.setEnabled(false);
            txtNom.setEnabled(true);
            txtNom.requestFocus();
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(GestionVendedores.class.getName()).log(Level.SEVERE, null, ex);
        }
        conf.habTexto(new Object[]{txtNom,txtDire,txtTel,txtCel});
        conf.habBoton(new Object[]{btnGrabar});
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
                 if(conf.mensajeResp("¿Desea grabar el registro?","El sistema comunica")) {
            grabar();
            conf.limpiarTexto(new Object[]{txtCod,txtNom,txtDire,txtTel,txtCel});
            conf.desTexto(new Object[]{txtCod,txtNom,txtDire,txtTel,txtCel});

        }
        btnNuevo.setEnabled(true);
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void tablaCobradoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCobradoresMouseClicked
                         int var=tablaCobradores.getSelectedRow();//capturamos el valor numerico de la fila cuando le damos clic
//        ponemos los valores de la tabla en los campos especificando la fila(var)y la columna
        txtCod.setText((String) tablaCobradores.getValueAt(var, 0));
        conf.habBoton(new Object[]{btnModificar,btnEliminar});
        
    }//GEN-LAST:event_tablaCobradoresMouseClicked

    private void tablaCobradoresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaCobradoresKeyReleased
                  int can=5;
            String titulos[] = {"Codigo","Nombre","Telefono","Celular","Direccion"};
            String consulta="SELECT * FROM "+tabla+" where "+campo+ " LIKE '%"+txtBuscar.getText()+"%'";
            System.out.print(consulta);
            String datos[]={"cod_cobrador","nom_cobrador","tel_cobrador","cel_cobrador","dire_cobrador"};
            sen.CargaTabla(tablaCobradores,titulos,consulta,datos,can);
            ///////////////////////
//            int ancho[]={50,90,90,90};
//            conf.TamañoTabla(tablaCobradores,ancho);
    }//GEN-LAST:event_tablaCobradoresKeyReleased

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
                              int mensaje= JOptionPane.showConfirmDialog(this,"¿Deseas cerrar esta ventana?","Salir",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        if(mensaje == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
       agrega=true;
        conf.desBoton(new Object[]{btnNuevo,btnModificar});
        conf.habTexto(new Object[]{txtCod,txtNom,txtDire,txtTel,txtCel});
    
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtDireKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireKeyTyped
       conf.habBoton(new Object[]{btnGrabar});
    }//GEN-LAST:event_txtDireKeyTyped

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
            Cancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        int can=5;
            String titulos[] = {"Codigo","Nombre","Direccion","Celular","Telefono"};
            String consulta="SELECT * FROM "+tabla+" where "+campo+ " LIKE '%"+txtBuscar.getText()+"%'";
            System.out.print(consulta);
            String datos[]={"cod_cobrador","nom_cobrador","dire_cobrador","cel_cobrador","tel_cobrador"};
            sen.CargaTabla(tablaCobradores,titulos,consulta,datos,can);
            ///////////////////////
            //conf.TamañoTabla(tablaCobradores,ancho);
    }//GEN-LAST:event_txtBuscarKeyReleased
 private void grabar() {
            if(agrega) {
                if(sen.ejecutarInser("insert into cobrador values("+ txtCod.getText()+","
                         + "'" + txtNom.getText()+"',"
                        + "'" + txtDire.getText()+"',"
                        + "" + txtCel.getText()+","
                        + "" + txtTel.getText()+""
                        + ")"))
                
                conf.mensaje(3,"El sistema comunica", "Hecho");
                    
            }
             else {
                    sen.ejecutarModif("Update cobrador set nom_cobrador='"+ txtNom.getText()+"',"
                        + "dire_cobrador='" +txtDire.getText()+"',"
                        + "cel_cobrador=" +txtCel.getText()+","
                        + "tel_cobrador=" +txtTel.getText()+""
                        + " where cod_cobrador= "+txtCod.getText()+"");
                
            }
                Actualizar();
                conf.limpiarTexto(new Object[]{txtCod,txtNom,txtDire,txtTel,txtCel});
    }
    private void CargaCobradores() throws SQLException {
            int can=5;
            String titulos[] = {"Codigo","Nombre","Direccion","Celular","Telefono"};
            String consulta="SELECT * FROM cobrador";
            
            String datos[]={"cod_cobrador","nom_cobrador","dire_cobrador","cel_cobrador","tel_cobrador"};
            sen.CargaTabla(tablaCobradores,titulos,consulta,datos,can);
            ///////////////////////
//            int ancho[]={50,90,90,90};
//            conf.TamañoTabla(tablaCobradores,ancho);
        }
        private void Actualizar() {
        try {
        CargaCobradores();
        
    } catch(SQLException ex) {
        Logger.getLogger(GestionCobradores.class.getName()).log(Level.SEVERE, null, ex);
    }
 
            
    
    }
        
                    private void Cancelar() {
        //metodo para Actualizar
        GestionCobradores asis = new GestionCobradores();
        asis.pack();
        asis.setVisible(true);
        dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionCobradores().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCobrosPendientes;
    private javax.swing.JButton btnCobrosRealizados;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel etiBuscarCobrador;
    private javax.swing.JLabel etiCelCobrador;
    private javax.swing.JLabel etiCodCobrador;
    private javax.swing.JLabel etiDireCobrador;
    private javax.swing.JLabel etiNomCobrador;
    private javax.swing.JLabel etiTelCobrador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCobradores;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCel;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtDire;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables

}
