/*
 * To change this  license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Funciones.Config;
import Funciones.conexion;
import Funciones.sentencias;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class GestionClientes extends javax.swing.JFrame {
sentencias sen=new sentencias();
conexion conn=new conexion();
Config conf=new Config();
boolean agrega=false;
private JTextField codigo; 
private String tabla="cliente";
private int cantidad;
private String dato[];
private String campo="nom_cliente";
    /**
     * Creates new form crearProveedor
     */
    public GestionClientes() {
        initComponents();
                        this.setLocationRelativeTo(null);
                        conf.desBoton(new Object[]{btnModificar,btnGrabar,btnEliminar});
        conf.desTexto(new Object[]{txtCod,txtRuc,txtNom,txtDire,txtTel,txtCel,txtCorreo,txtNotas,txtRef});
        this.setResizable(false);

        
    }
    
public void cargarDatos(String[] titulos,String consultas,String[] dato,int cantidad,int tam[],String tabla, String campo){
 this.tabla=tabla;
 this.cantidad=cantidad;
 this.dato=dato;
 this.campo=campo;
    String consulta=consultas+this.tabla;
     sen.CargaTabla(tablaCliente, titulos, consulta, dato, this.cantidad);
        conf.TamañoTabla(tablaCliente, tam);  
       
}
  public void buscarElementos() throws SQLException {
   javax.swing.table.DefaultTableModel dt=(DefaultTableModel)tablaCliente.getModel();
   int cantidadfila= dt.getRowCount();        
        for( int i=cantidadfila-1; i>=0; i--) 
              dt.removeRow(i);
     try {
         String sql="SELECT * FROM "+tabla+" where "+campo+ " LIKE '%"+txtBuscarCliente.getText()+"%'";
         System.out.println(sql);
         ResultSet rsa=sen.consultas(sql);
        String datos[]=new String[cantidad];
      while(rsa.next()){
    for(int i=0; i<cantidad;i++){
        datos[i]=rsa.getString(dato[i]);
    }
    dt.addRow(datos);
}
    tablaCliente.setModel(dt);
     } catch (SQLException ex) {
         Logger.getLogger(GestionClientes.class.getName()).log(Level.SEVERE, null, ex);
     }
        
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        etiNomCliente = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        etiCodCliente = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        etiRucCliente = new javax.swing.JLabel();
        txtRuc = new javax.swing.JTextField();
        etiDireCliente = new javax.swing.JLabel();
        txtDire = new javax.swing.JTextField();
        etiTelCliente = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        etiCelCliente = new javax.swing.JLabel();
        txtCel = new javax.swing.JTextField();
        etiCorreoCliente = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        etiNotasCliente = new javax.swing.JLabel();
        txtNotas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();
        etiBuscarCliente = new javax.swing.JLabel();
        txtBuscarCliente = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnFacturasClientes = new javax.swing.JButton();
        btnCobrosClientes = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        etiCorreoCliente1 = new javax.swing.JLabel();
        txtRef = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setBackground(new java.awt.Color(0, 0, 51));
        jLabel1.setFont(new java.awt.Font("Raleway", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        jLabel1.setText("GESTIÓN de CLIENTES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        etiNomCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiNomCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/usuarioMenu.png"))); // NOI18N
        etiNomCliente.setText("Nombre");
        getContentPane().add(etiNomCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        getContentPane().add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 190, 30));

        etiCodCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiCodCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/cod.png"))); // NOI18N
        etiCodCliente.setText("Código");
        getContentPane().add(etiCodCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        getContentPane().add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 190, 30));

        etiRucCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiRucCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/ruc.png"))); // NOI18N
        etiRucCliente.setText("RUC");
        getContentPane().add(etiRucCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        getContentPane().add(txtRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 190, 30));

        etiDireCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiDireCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/dire.png"))); // NOI18N
        etiDireCliente.setText("Dirección");
        getContentPane().add(etiDireCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));
        getContentPane().add(txtDire, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 190, 30));

        etiTelCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiTelCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/tel.png"))); // NOI18N
        etiTelCliente.setText("Teléfono");
        getContentPane().add(etiTelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));
        getContentPane().add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 190, 30));

        etiCelCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiCelCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/cel.png"))); // NOI18N
        etiCelCliente.setText("Celular");
        getContentPane().add(etiCelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));
        getContentPane().add(txtCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 190, 30));

        etiCorreoCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiCorreoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/correo.png"))); // NOI18N
        etiCorreoCliente.setText("Correo");
        getContentPane().add(etiCorreoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 190, 30));

        etiNotasCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiNotasCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/document.png"))); // NOI18N
        etiNotasCliente.setText("Notas");
        getContentPane().add(etiNotasCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, -1, -1));

        txtNotas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNotasKeyTyped(evt);
            }
        });
        getContentPane().add(txtNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 630, 190, 30));

        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "RUC", "Direccion", "Teléfono", "Celular"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 590, 290));

        etiBuscarCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        etiBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        etiBuscarCliente.setText("Buscar");
        getContentPane().add(etiBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, -1, -1));

        txtBuscarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarClienteKeyReleased(evt);
            }
        });
        getContentPane().add(txtBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 380, 50));

        btnEliminar.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 480, 120, 50));

        btnNuevo.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inserto.png"))); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 110, 50));

        btnModificar.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        btnModificar.setText("EDITAR");
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 110, 50));

        btnGrabar.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        btnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnGrabar.setText("GRABAR");
        btnGrabar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, 120, 50));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/exitMenu.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 390, 90, 50));

        btnFacturasClientes.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        btnFacturasClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/documento.png"))); // NOI18N
        btnFacturasClientes.setText("HISTORIAL DE FACTURAS");
        getContentPane().add(btnFacturasClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 590, 290, 60));

        btnCobrosClientes.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        btnCobrosClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/documento.png"))); // NOI18N
        btnCobrosClientes.setText("COBROS PENDIENTES");
        getContentPane().add(btnCobrosClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 590, 290, 60));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Facturación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Raleway", 1, 14))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 560, 610, 110));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/CErrar2.png"))); // NOI18N
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 480, 60, 50));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Raleway", 1, 14))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 610, 100));

        etiCorreoCliente1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiCorreoCliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/persons.png"))); // NOI18N
        etiCorreoCliente1.setText("Contacto");
        getContentPane().add(etiCorreoCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));
        getContentPane().add(txtRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, 190, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
                  if(conf.mensajeResp("Desea eliminar el registro", "EL SISTEMA AVISA:")) {
            sen.ejecutarBorrad("delete from cliente where cod_cliente=" +txtCod.getText());
        }
        Actualizar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
               
        String sql="select * from cliente where cod_cliente= "+ txtCod.getText();
        ResultSet rs=sen.consultas(sql);//recibimos la consulta en una variable ResultSet
        try {
            while(rs.next()) { //mientras hay datos en rs
                //cargamos en los campos el resultado de rs, getString obtiene el valor de
                //la base de datos segun la columna numerica.
                txtRuc.setText(rs.getString(3));
                txtNom.setText(rs.getString(2));
                txtDire.setText(rs.getString(4));
                txtTel.setText(rs.getString(5));
                txtCel.setText(rs.getString(6));
                txtRef.setText(rs.getString(7));
                txtCorreo.setText(rs.getString(8));
                txtNotas.setText(rs.getString(9));

            }

            btnNuevo.setEnabled(false);
            txtRuc.setEnabled(true);
            txtRuc.requestFocus();
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(GestionClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        conf.habTexto(new Object[]{txtRuc,txtNom,txtDire,txtTel,txtCel,txtCorreo,txtNotas,txtRef});
        conf.habBoton(new Object[]{btnGrabar});
        conf.desBoton(new Object[]{btnEliminar});
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
             if(conf.mensajeResp("¿Desea grabar el registro?","El sistema comunica")) {
            grabar();
            conf.limpiarTexto(new Object[]{txtCod,txtRuc,txtNom,txtDire,txtTel,txtCel,txtCorreo,txtRef,txtNotas});
            conf.desTexto(new Object[]{txtCod,txtRuc,txtNom,txtDire,txtTel,txtCel,txtCorreo,txtRef,txtNotas});

        }
        btnNuevo.setEnabled(true);
        conf.desBoton(new Object[]{btnGrabar,btnModificar});
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void tablaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClienteMouseClicked
                  int var=tablaCliente.getSelectedRow();//capturamos el valor numerico de la fila cuando le damos clic
//        ponemos los valores de la tabla en los campos especificando la fila(var)y la columna
        txtCod.setText((String) tablaCliente.getValueAt(var, 0));
        conf.habBoton(new Object[]{btnModificar,btnEliminar});
        conf.desBoton(new Object []{btnNuevo});
        
    }//GEN-LAST:event_tablaClienteMouseClicked

    private void txtBuscarClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarClienteKeyReleased
          int can=6;
            String titulos[] = {"Codigo","RUC","Nombre","Telefono","Celular","Contacto"};
            String consulta="SELECT * FROM "+tabla+" where "+campo+ " LIKE '%"+txtBuscarCliente.getText()+"%'";
            System.out.print(consulta);
            String datos[]={"cod_cliente","ruc_cliente","nom_cliente","tel_cliente","cel_cliente","ref_cliente"};
            sen.CargaTabla(tablaCliente,titulos,consulta,datos,can);
            ///////////////////////
            int ancho[]={50,120,150,90,90,90};
            conf.TamañoTabla(tablaCliente,ancho);
    }//GEN-LAST:event_txtBuscarClienteKeyReleased

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
                      int mensaje= JOptionPane.showConfirmDialog(this,"¿Deseas cerrar esta ventana?","Salir",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        if(mensaje == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
      agrega=true;
        conf.desBoton(new Object[]{btnNuevo,btnModificar});
        conf.habTexto(new Object[]{txtCod,txtRuc,txtNom,txtDire,txtTel,txtCel,txtCorreo,txtNotas,txtRef});
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtNotasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNotasKeyTyped
       conf.habBoton(new Object[]{btnGrabar});
    }//GEN-LAST:event_txtNotasKeyTyped

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       Cancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Actualizar();
    }//GEN-LAST:event_formWindowOpened
    private void grabar() {
            if(agrega) {
                if(sen.ejecutarInser("insert into cliente values("+ txtCod.getText()+","
                         + "'" + txtNom.getText()+"',"
                        + "'" + txtRuc.getText()+"',"
                        + "'" + txtDire.getText()+"',"
                        + "" + txtTel.getText()+","
                        + "" + txtCel.getText()+","
                        + "'" + txtRef.getText()+"',"
                        + "'" + txtCorreo.getText()+"',"
                        + "'" + txtNotas.getText()+"'"
                        + ")"))
                
                conf.mensaje(3,"El sistema comunica", "Hecho");
                    
            }
             else {
                    sen.ejecutarModif("Update cliente set ruc_cliente='"+ txtRuc.getText()+"',"
                        + "nom_cliente='" +txtNom.getText()+"',"
                        + "dire_cliente='" +txtDire.getText()+"',"
                        + "tel_cliente=" +txtTel.getText()+","
                        + "cel_cliente=" +txtCel.getText()+","
                        + "ref_cliente='" +txtRef.getText()+"',"
                        + "correo_cliente='" +txtCorreo.getText()+"',"
                        + "obs_cliente='" +txtNotas.getText()+"'"
                        + " where cod_cliente=  "+txtCod.getText()+"");
                
            }
                Actualizar();
                conf.limpiarTexto(new Object[]{txtCod,txtRuc,txtNom,txtDire,txtTel,txtCel,txtCorreo,txtNotas});
    }
    private void CargaClientes() throws SQLException {
            int can=6;
            String titulos[] = {"Codigo","RUC","Nombre","Telefono","Celular","Contacto"};
            String consulta="SELECT * FROM cliente";
            
            String datos[]={"cod_cliente","ruc_cliente","nom_cliente","tel_cliente","cel_cliente","ref_cliente"};
            sen.CargaTabla(tablaCliente,titulos,consulta,datos,can);
            ///////////////////////
            int ancho[]={50,120,150,90,90,90};
            conf.TamañoTabla(tablaCliente,ancho);
        }
        private void Actualizar() {
        try {
        CargaClientes();
        
    } catch(SQLException ex) {
        Logger.getLogger(GestionClientes.class.getName()).log(Level.SEVERE, null, ex);
    }
 
            
    
    }
        
                    private void Cancelar() {
        //metodo para Actualizar
        GestionClientes asis = new GestionClientes();
        asis.pack();
        asis.setVisible(true);
        dispose();
    }
 
        
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCobrosClientes;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFacturasClientes;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel etiBuscarCliente;
    private javax.swing.JLabel etiCelCliente;
    private javax.swing.JLabel etiCodCliente;
    private javax.swing.JLabel etiCorreoCliente;
    private javax.swing.JLabel etiCorreoCliente1;
    private javax.swing.JLabel etiDireCliente;
    private javax.swing.JLabel etiNomCliente;
    private javax.swing.JLabel etiNotasCliente;
    private javax.swing.JLabel etiRucCliente;
    private javax.swing.JLabel etiTelCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCliente;
    private javax.swing.JTextField txtBuscarCliente;
    private javax.swing.JTextField txtCel;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDire;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtNotas;
    private javax.swing.JTextField txtRef;
    private javax.swing.JTextField txtRuc;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables

}
